Update hello-helidon with configmap support
verrazzano/examples pull request #63
Opened 2021-04-08 14:42 UTC by arjav-desai

VZ-2307

2021-04-08 18:59 UTC, kminder commented on hello-helidon/README.md
> +This example application has two endpoint/flavors
Needs to be reviewed by @rosemarymarano

2021-04-08 19:01 UTC, kminder commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/Main.java
> +            //System.out.println("http://localhost:" + server.port() + "/config");
Should these commented out lines be removed?

2021-04-08 19:03 UTC, kminder commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/Main.java
> +        LOGGER.info("Loaded config are: " + config.get("config.greeting"));
Wording feels off.  "Configured greeting is:" perhaps?

2021-04-08 19:04 UTC, kminder commented on hello-helidon/helidon-app-greet-v2/src/main/java/io/helidon/examples/quickstart/mp/Main.java
> +            //System.out.println("http://localhost:" + server.port() + "/config");
Remove commented out lines?

2021-04-08 19:08 UTC, arjav-desai commented on hello-helidon/README.md
> +This example application has two endpoint/flavors
Add @rosemarymarano as reviewer.

2021-04-08 19:27 UTC, rosemarymarano reviewed
Lots of edits. Please let me know when you are done incorporating them. Also, if you have any questions on them.

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- /greet which uses micro-profile properties file as config source
/greet which -> `/greet`, which (code font and a comma)
source -> source. (period at the end of the sentence)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- /config which uses k8s configmap as config source
/config which -> `/config`, which (code font and a comma)
k8s configmap -> Kubernetes ConfigMap
source -> source. (period at the end of the sentence)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
>  ### Install the Example Application
Install the Example Application -> Install the example application

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +Detailed instructions for installing Hello World Helidon can be found
can be found -> can be found at: (colon)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +This example application has two endpoint/flavors
endpoint/flavors -> endpoints: (should be plural, colon at the end)
Not sure why you are using the term flavors. Do you mean that the example application has two variations? Or, something else?

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- /greet which uses micro-profile properties file as config source
/greet which -> `/greet`, which (code font and comma)
uses micro-profile -> uses a microprofile
as config source -> as a configuration source. (period at the end of a sentence)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- /config which uses k8s configmap as config source
/config which -> `/config`, which (code font and comma)
uses k8s configmap -> uses a Kubernetes ConfigMap
as config source -> as a configuration source. (period at the end of a sentence)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
>  ### Install the Example Application
Install the Example Application -> Install the example application

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +Detailed instructions for installing Hello World Helidon can be found
can be found -> can be found at: (colon)

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- [/greet](https://github.com/verrazzano/verrazzano/blob/master/examples/hello-helidon/README.md).
[/greet] -> This points to the Hello World Helidon README and should be described as such.
No period is needed at the end of this bulleted item.

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
> +- [/config](https://github.com/verrazzano/verrazzano/blob/master/examples/helidon-config/README.md).
[/config] -> This returns a 404 Error.
No period is needed at the end of this bulleted item.

2021-04-08 19:27 UTC, rosemarymarano commented on hello-helidon/README.md
>  This example application provides a simple *Hello World* REST service written with [Helidon](https://helidon.io).
*Hello World* -> Hello World (no need for italics)

2021-04-08 19:29 UTC, markxnelson requested changes
comments apply to all occurrences of the same issue, not just the one where they are mentioned

2021-04-08 19:29 UTC, markxnelson commented on hello-helidon/helidon-app-greet-v1/pom.xml
> +            <groupId>jakarta.activation</groupId>
this is a new dependency and requires approval

2021-04-08 19:29 UTC, markxnelson commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigProvider.java
> +/**
blank line before comment

2021-04-08 19:29 UTC, markxnelson commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigResource.java
> +package io.helidon.examples.quickstart.mp;
new line after copyright header

2021-04-08 19:29 UTC, markxnelson commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigProvider.java
> +package io.helidon.examples.quickstart.mp;
blank line after license header

2021-04-08 19:48 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v1/pom.xml
> +            <groupId>jakarta.activation</groupId>
helidon 2.2.1 has brings 1.2.2 of this API based on https://github.com/oracle/helidon/blob/2.2.1/dependencies/pom.xml#L39

2021-04-08 19:51 UTC, rosemarymarano commented on hello-helidon/README.md
> +- [/config](https://github.com/verrazzano/verrazzano/blob/master/examples/helidon-config/README.md).
That's fine, but please use something more descriptive in the link text.

2021-04-08 19:58 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/Main.java
> +            //System.out.println("http://localhost:" + server.port() + "/config");
Removed commented line.

2021-04-08 19:58 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v2/src/main/java/io/helidon/examples/quickstart/mp/Main.java
> +            //System.out.println("http://localhost:" + server.port() + "/config");
Uncommented it.

2021-04-08 19:59 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigProvider.java
> +/**
Added blank line.

2021-04-08 19:59 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigResource.java
> +package io.helidon.examples.quickstart.mp;
Added blank line.

2021-04-08 19:59 UTC, arjav-desai commented on hello-helidon/helidon-app-greet-v1/src/main/java/io/helidon/examples/quickstart/mp/ConfigProvider.java
> +package io.helidon.examples.quickstart.mp;
Added blank line.

2021-04-08 20:03 UTC, rosemarymarano reviewed
Much better. Thank you.

2021-04-08 20:03 UTC, rosemarymarano commented on hello-helidon/README.md
> +- `/greet`, which uses microprofile properties file as a configuration source. Installation instructions are specified as part of [hello-helidon](https://github.com/verrazzano/verrazzano/blob/master/
uses microprofile -> uses a microprofile
Installation instructions are specified as part of -> For installation instructions, see [hello-helidon](https://github.com/verrazzano/verrazzano/blob/master/examples/hello-helidon/README.md).

2021-04-08 20:03 UTC, rosemarymarano commented on hello-helidon/README.md
> +- `/config`, which uses a Kubernetes ConfigMap as a configuration source. Installation instructions are specified as part of [helidon-config](https://github.com/verrazzano/verrazzano/blob/master/exam
Installation instructions are specified as part of -> For installation instructions, see [helidon-config](https://github.com/verrazzano/verrazzano/blob/master/examples/helidon-config/README.md).

2021-04-08 20:34 UTC, arjav-desai commented on hello-helidon/README.md
> +- `/greet`, which uses microprofile properties file as a configuration source. Installation instructions are specified as part of [hello-helidon](https://github.com/verrazzano/verrazzano/blob/master/
updated.

2021-04-08 20:35 UTC, arjav-desai commented on hello-helidon/README.md
> +- `/config`, which uses a Kubernetes ConfigMap as a configuration source. Installation instructions are specified as part of [helidon-config](https://github.com/verrazzano/verrazzano/blob/master/exam
fixed.

2021-04-08 20:40 UTC, rosemarymarano approved these changes

2021-04-09 12:34 UTC, markxnelson approved these changes

2021-04-09 12:53 UTC, merged